### ISSUE TITLE
Highlighting the color changing text on the main page doesn't work correctly

### ISSUE THREAD

**Issue by maximium91** [lancerossdev/lanceross-xyz#1]
Highlighting the rainbow text here makes it unreadable, 
 
https://user-images.githubusercontent.com/107336266/191398325-92a87b3c-4347-405a-8888-1fa24e6fa24f.mp4

**Comment by lancerossdev** [comment]
Yeah, I'm currently changing it just to plain white (inherited color from parent). Wait for like a few days, I'm revamping my site with new UI because why not 😎
